### PR TITLE
Add GitHub API token to request

### PR DESCRIPTION
**Pull request by xxsimoxx**
Add GitHub API token to request to `mu-plugins/software-submit-form.php`.

### CODE REVIEW

**Comment by KTS915** [comment]
This should prove temporary, because we should at some point get the directory working in a way that renders the Update plugin unnecessary. But we might as well include it for the moment.

**Comment by xxsimoxx** [comment]
> This should prove temporary, because we should at some point get the directory working in a way that renders the Update plugin unnecessary. But we might as well include it for the moment.

Sorry but can't understand what using API token has to do with the Update plugin...

**Comment by KTS915** [comment]
From PM, I thought you meant that this was just for Update Manager.

**Comment by xxsimoxx** [comment]
Sorry... it was my PM that was wrong.

**Pull request merged**
