### PR TITLE
Get headers from ZIP

### PR DESCRIPTION
**Pull request by xxsimoxx**
This PR substitutes #18 that can be closed.

Get headers from submitted ZIP file.
`$headers` contains the plugin headers.
`$main_plugin_file` contain the relative path of the plugin main file (like `doit/bad.php`).

You can test plugin doing thing not in the proper way using my [Do It Bad](https://github.com/xxsimoxx/doit/releases/download/v1.0.0/doit-1.0.0.zip) plugin.

### CODE REVIEW

**Comment by KTS915** [comment]
This is much more along the lines I'm thinking of, but it still looks for the "Name" header, which is actually completely irrelevant for the purposes of the Directory.

One of the reasons why this is important can be seen [here](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/): "Since WordPress 5.8 plugin [readme files are not parsed for requirements](https://core.trac.wordpress.org/ticket/48520). This means that headers Requires PHP and Requires at least are going to be parsed from plugin’s main PHP file."

So, if we're looking for the "Name" header in a PHP file of a plugin also intended to work with WP, it might well not be there, whereas the "Requires PHP" header that we DO need will be. So "Requires PHP" is what we should be checking for.

This also has me thinking now, as Joy has previously argued, that this is where the "Requires CP" minimum version header should go (especially as it's the only other header we need, apart possibly from "Description" as a fallback if there's no README.md to parse).

**Comment by xxsimoxx** [comment]
We also can check for both in "or" mode.
I'm insisting for that field because in this code the important thing is that we find the right file. And it's the way CP determines what is the main file.
Then, when we got it, we can enforce the requirement of every header we want.

**Comment by KTS915** [comment]
We will already have other checks in place to find the right file. That's the point of having the slug and Update URI, both of which have to be unique to the particular software. Let's check for what we need, not for what we don't need. I'm happy to look in different places but, as I've said, the only things we need from the headers are "Requires PHP", "Requires CP" and maybe "Description".

**Comment by xxsimoxx** [comment]
Tomorrow i'll push a commit to use "Requires PHP".

**Comment by KTS915** [comment]
I have now uploaded a new file that will facilitate our checking that we don't permit duplicate software slugs: https://github.com/KTS915/Test-ClassicPress-Directory/blob/main/mu-plugins/slug-taxonomies.php

I have some edits for the `submit-software-form.php` file that go with that, so you probably want to hold off on a new PR until you've seen them. I'll try to get them done later today, but it might be tomorrow instead.

**Comment by KTS915** [comment]
OK, I have now uploaded an updated version of the `submit-software-form.php` file, together with `Parsedown.php` in the `mu-plugins` folder (for parsing Markdown in README.md files), with the plugin header "Description" being used as a fallback.

At the moment, we aren't getting any headers from themes and snippets, whereas it would be much better if we could get at least Requires PHP and Requires CP (minimum version).

It looks like we should be adopting the same approach to themes as we are now moving towards for plugins, so the code will need re-writing to take account of that. For snippets, it should also be much the same except that there will be only one file, so it should be much easier to get the information. (Of course, both these ideas depend on developers being prepared to adopt these standards, but they seem quite minimal really, and we can still use the README.md file for the main description).

**Comment by xxsimoxx** [comment]
Agree with you.
We should do the same for themes and let's see what to do for snippets.
Commits are getting messy, so I'm going to close also this.
For now I'm doing 2 little PR:
- one to fix a bug with headers in the main branch (already done #21)
- one to use GitHub API token also in `submit-software-form.php` ~that I'm preparing~ (already done #22 )

If you merge those we can start working on a cleaner `main` branch.

**Pull request closed without merging**
