### PR TITLE
Inspect zip

### PR DESCRIPTION
**Pull request by xxsimoxx**
This PR gets the slug even if the plugin main file is something like `doit/bad.php`.
Also `$headers` get valorized using the plugin headers (at the moment is not used).

## Things to be careful with this PR
- Please remove  `mu-plugins/download-links.php` from this PR. It can be easily done before merging (for people with write access. for me it's a git mess :-)). Only `mu-plugins/software-submit-form.php` changes belong to this PR.
- Needs more testing.

### CODE REVIEW

**Review by KTS915 — COMMENTED** [review]
This looks good, but I'm not sure about lines 421 and 435, where I'm wondering if `$file_data = $zip->getFromName( $guessed_slug, 8192 )` should be `$file_data === $zip->getFromName( $guessed_slug, 8192 )`

**Comment by KTS915** [comment]
Further testing shows that this doesn't get the correct slug. With my Table of Contents plugin, this PR says that the slug is `kts-table-of-contents/table-of-contents.php`, whereas without the PR, the slug is correctly retrieved as `kts-table-of-contents`

**Comment by KTS915** [comment]
I think this is the way to go:
```

	# Find slug from top level folder name
	$zip = new ZipArchive();
	$zip->open( $file['tmp_name'] );
	$slug = false;
	$basedir = strstr( $zip->getNameIndex(0), '/', true );

	# Deal with themes
	if ( $post_type === 'theme' ) {
		$slug = $basedir;
		$headers = [];
	}

	# Check if most common slug contain headers
	$guessed_slug = $basedir . '/' . $basedir . '.php';
	if ( $slug === false ) {
		$file_data = $zip->getFromName( $guessed_slug, 8192 );
		$headers = kts_get_plugin_data( $file_data );
		if ( isset( $headers['Name'] ) && $headers['Name'] !== '' ) {
			$slug = $basedir;
		}
	}

	if ( $slug === false ) {

		# Parse other files for headers
		for ( $i = 0; $i < $zip->numFiles; $i++ ) {
			if ( ! preg_match( '~\.php$~', $zip->getNameIndex( $i ) ) || substr_count( $zip->getNameIndex( $i ), '/' ) !== 1 ) {

			        # Only check PHP and don't recourse into subdirs
				continue;
			}
			$file_data = $zip->getFromIndex( $i, 8192 );
			$headers = kts_get_plugin_data( $file_data );
			if ( isset( $headers['Name'] ) && $headers['Name'] !== '' ) {
				$slug = strstr( $zip->getNameIndex( $i ), '/', true );
				break;
			}
		}
	}
```

**Comment by KTS915** [comment]
Looking again at Issue 17, I think there might be a misunderstanding here, and that the new code to find the slug is unnecessary. (Good for the headers, but unnecessary for the slug.) That's because the "slug" for our purposes is what you have here as `$basedir`. So I'm thinking we can simplify the above code.

**Comment by KTS915** [comment]
So now I'm thinking this looks better:
```
	# Find slug from top level folder name
	$zip = new ZipArchive();
	$zip->open( $file['tmp_name'] );
	$slug = strstr( $zip->getNameIndex(0), '/', true );

	# Deal with themes and code snippets
	if ( in_array( $post_type, ['theme', 'snippet'] ) ) {
		$headers = [];
	}
	else {
		# Check if most common location for main file contain headers
		$guessed_main_file = $slug . '/' . $slug . '.php';
		$file_data = $zip->getFromName( $guessed_main_file, 8192 );
		$headers = kts_get_plugin_data( $file_data );

		if ( empty( $headers['RequiresPHP'] ) ) {

			# Parse other files for headers
			for ( $i = 0; $i < $zip->numFiles; $i++ ) {
				if ( ! preg_match( '~\.php$~', $zip->getNameIndex( $i ) ) || substr_count( $zip->getNameIndex( $i ), '/' ) !== 1 ) {

					# Only check PHP and don't recourse into subdirs
					continue;
				}
				$file_data = $zip->getFromIndex( $i, 8192 );
				$headers = kts_get_plugin_data( $file_data );
			}
		}
	}
```

**Comment by xxsimoxx** [comment]
Ok, the problem was I've a wrong idea of the slug, as I intended it as in Update Manager: `plugin-dir-name/plugin-base-file.php`.
So the code you are proposing looks good.
I think I'll do another PR (also so it don't conflicts) with the code [above](https://github.com/KTS915/Test-ClassicPress-Directory/pull/18#issuecomment-1198602991).
I'll change:
- `if ( empty( $headers['RequiresPHP'] ) ) {` because `RequiresPHP` is one of the most unused headers
- add an exit from the loop when we have the headers, because as now it completes the loop on all files and exit with the headers of the last file that can be empty.

**Comment by KTS915** [comment]
OK, but Requires PHP is actually the most important header for us. The others really don't matter (except for one specifying the minimum version of CP, which a plugin designed primarily for WP won't have anyway).

**Comment by xxsimoxx** [comment]
I think this can be enforced, automatically or in the review process, but `$plugin_data['Name']` is what CP uses to determine which file has headers into.

**Comment by KTS915** [comment]
When you say it's what CP uses, what do you mean? The Directory doesn't care about the Name at all (because the developer puts that into the submission form manually), but it does care about the minimum version of PHP.

**Comment by smileBeda** [comment]
Regarding `Requires PHP`:

https://docs.classicpress.net/plugin-guidelines/plugin-header-requirements/ says `Requires PHP` does not work in non-WP Hosted Plugins.
While we (CP) do indeed have the code added in WP-5.3.0 for that header tag in core, you can easily _activate_ plugins requiring PHP 10 on a CP Install.

So I believe the `Requires PHP` is merely something that the _api_ checks when _installing_  a plugin (from WP), not when _activating_ it.
The only currently existing integration to actually _install_ plugins from CP is the Directory Integration I made and I do not check for PHP versions.
It will be cool to have it, of course, however if we add / support it, we have to update the DOC soon because basically all plugins so far in the directory have not been checked for that header value at all (and may or may not include it).

Regarding important tags:
_The_ most important headers are the `Plugin Name` and `Version`. We can _not_ rely only on Directory data when the plugin is installed on the system and we try to fetch an update for it.
Without these tags, you cannot "deal" with the `doit/bad.php` cases, and you cannot decide if a plugin needs an update, when checking from remote. So I would probably try to fetch them from the file when adding the item in the Directory (if possible) to avoid any mistake-issues.

**Comment by KTS915** [comment]
The docs are irrelevant because they relate to the current directory and not what we are building. In the directory we are building, Requires PHP is going to matter, so we can avoid causing a white screen for users.

**Comment by xxsimoxx** [comment]
> When you say it's what CP uses, what do you mean? The Directory doesn't care about the Name at all (because the developer puts that into the submission form manually), but it does care about the minimum version of PHP.

It's used in `get_plugins` to choose what code to run.

**Comment by KTS915** [comment]
But that has nothing to do with the Directory. You're talking about core.

**Comment by xxsimoxx** [comment]
Yes, sorry! I've used it because core considers it the most "easy" to find out (or at least I think they thought that).

**Comment by xxsimoxx** [comment]
For me it's OK to close this and go on with #19 .

**Comment by KTS915** [comment]
Just wanted to add a reply to @smileBeda's comment that "The most important headers are the Plugin Name and Version. We can not rely only on Directory data when the plugin is installed on the system and we try to fetch an update for it."

Actually, we will be able to do just that in the new Directory. We are registering both the software's slug and an Update URI for the software when it is first submitted, and all subsequent updates will be recognized only if they adhere to them, while any new version number will be parsed from the download link itself (not the header) and must be greater than the previous version.

So the only headers we need to find are actually "Requires PHP" and "Requires at least CP", though you can also add "Description" to that as a fallback if we can't find a README.md file.

**Comment by xxsimoxx** [comment]
Closing this. See #19.

**Pull request closed without merging**
